const home=document.querySelector('.home'),apps=[...document.querySelectorAll('.screen.app')],reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;
const cuteSheet=document.createElement('link');cuteSheet.rel='stylesheet';cuteSheet.href='cute.css';document.head.append(cuteSheet);
const phone=document.querySelector('.phone'),layer=document.createElement('div');layer.className='cute-layer';phone.append(layer);
function currentScreen(){return document.querySelector('.screen.active')}
function confetti(kind,x,y,count=5){if(reduced)return;for(let n=0;n<count;n++){const bit=document.createElement('i');bit.className=kind==='heart'?'heart-burst':'spark-burst';bit.textContent=kind==='heart'?(n%2?'♡':'♥'):(n%2?'✦':'✧');bit.style.left=(x+(Math.random()-.5)*14)+'px';bit.style.top=(y+(Math.random()-.5)*12)+'px';bit.style.setProperty('--x',((Math.random()-.5)*55)+'px');bit.style.setProperty('--y',((Math.random()-.5)*55)+'px');layer.append(bit);setTimeout(()=>bit.remove(),1000)}}
function paws(x,y){if(reduced)return;[0,1,2].forEach(n=>{const paw=document.createElement('i');paw.className='paw';paw.textContent='🐾';paw.style.left=(x+n*13)+'px';paw.style.top=(y+(n%2)*8)+'px';layer.append(paw);setTimeout(()=>paw.remove(),2400)})}
function cat(text,classes){const c=document.createElement('button');c.type='button';c.className='cat '+classes;c.textContent=text;c.setAttribute('aria-label','A cute cat');c.onclick=e=>{e.stopPropagation();c.classList.remove('cat-jump');void c.offsetWidth;c.classList.add('cat-jump');const r=phone.getBoundingClientRect();confetti('heart',e.clientX-r.left,e.clientY-r.top,5);paws(e.clientX-r.left,e.clientY-r.top+10);if(c.classList.contains('home-cat')){c.classList.add('awake');document.querySelector('.cat-zzz')?.remove();say('yawn... meow ♡',38,phone.clientHeight-118)}setTimeout(()=>c.classList.remove('cat-jump','awake'),800)};layer.append(c);return c}
function say(message,x,y){const bubble=document.createElement('span');bubble.className='cat-bubble';bubble.textContent=message;bubble.style.left=x+'px';bubble.style.top=y+'px';layer.append(bubble);setTimeout(()=>bubble.remove(),1000)}
function installHomeCat(){if(document.querySelector('.home.active')&&!layer.querySelector('.home-cat')){cat('🐱','home-cat');const z=document.createElement('i');z.className='cat-zzz';z.textContent='Zzz';layer.append(z)}}
function screenSurprise(id){layer.querySelectorAll('.app-cat,.music-cat,.final-cat,.notification,.message-reaction').forEach(x=>x.remove());if(id==='messages'){const n=document.createElement('span');n.className='notification';n.textContent='♡ new little message';layer.append(n);const r=document.createElement('span');r.className='message-reaction';r.textContent='♡';layer.append(r)}if(id==='music')cat('🐱🎧','music-cat app-cat');if(id==='notes'){const s=document.createElement('span');s.className='notes-sticker';s.textContent='🐱✦';layer.append(s)}if(id==='secret')cat('🐱','app-cat');if(id==='final-message')cat('🐈','final-cat')}
document.head.insertAdjacentHTML('beforeend','<style>.screen.app{display:block;justify-items:normal;gap:0;cursor:auto;text-shadow:none;font-weight:400;font-size:initial;border:0;background:linear-gradient(160deg,#fffafd,#f8edf4 58%,#f3e8ef)}</style>');
function openApp(name){const next=document.getElementById(name);if(!next)return;apps.forEach(x=>x.classList.remove('active'));home.classList.remove('active');layer.querySelectorAll('.home-cat,.cat-zzz').forEach(x=>x.remove());next.classList.add('active');screenSurprise(name)}
function goHome(){apps.forEach(x=>x.classList.remove('active'));home.classList.add('active');installHomeCat();say('welcome back ♡',38,phone.clientHeight-118)}
installHomeCat();
phone.addEventListener('click',e=>{const r=phone.getBoundingClientRect(),x=e.clientX-r.left,y=e.clientY-r.top;if(e.target.closest('.app, .back, .play, .open, .heart, .particles'))confetti('heart',x,y,4);if(e.target.closest('.particles'))confetti('spark',x,y,7);});
document.querySelector('.open').addEventListener('click',()=>{const magic=document.createElement('span');magic.className='secret-magic';layer.append(magic);confetti('heart',phone.clientWidth/2,phone.clientHeight*.48,14);confetti('spark',phone.clientWidth/2,phone.clientHeight*.48,10);setTimeout(()=>magic.remove(),700)});
let indicatorTaps=0;document.querySelector('.indicator').addEventListener('click',e=>{indicatorTaps++;e.currentTarget.classList.add('party');setTimeout(()=>e.currentTarget.classList.remove('party'),800);if(indicatorTaps===3){say('tiny home magic unlocked! ♡',62,phone.clientHeight-88);cat('🐾','peek-cat');indicatorTaps=0}});
if(!reduced){setInterval(()=>{if(!document.hidden&&Math.random()>.38){const c=cat('🐈','wandering-cat');setTimeout(()=>c.remove(),8300)}},18000);setInterval(()=>{if(!document.hidden&&Math.random()>.5){const h=document.createElement('i');h.className='tiny-heart';h.textContent=Math.random()>.5?'♡':'✦';h.style.left=(30+Math.random()*(phone.clientWidth-60))+'px';h.style.bottom='48px';layer.append(h);setTimeout(()=>h.remove(),3600)}},11000)}
document.querySelectorAll('[data-app]').forEach(x=>x.onclick=()=>openApp(x.dataset.app));document.querySelectorAll('.back').forEach(x=>x.onclick=goHome);document.querySelector('.open').onclick=()=>{const s=document.querySelector('.secret');s.classList.add('reveal');setTimeout(()=>{s.classList.remove('reveal');openApp('final-message')},reduced?0:480)};
const box=document.querySelector('.lightbox'),large=box.querySelector('img');document.querySelectorAll('.gallery img').forEach(img=>img.parentElement.onclick=()=>{large.src=img.src;large.alt=img.alt;box.classList.add('show');box.setAttribute('aria-hidden','false')});function close(){box.classList.remove('show');box.setAttribute('aria-hidden','true')}box.onclick=e=>{if(e.target===box||e.target.tagName==='BUTTON')close()};document.onkeydown=e=>{if(e.key==='Escape')close()};
